### ISSUE TITLE
show version

### ISSUE THREAD

**Issue by mu853** [hichtakk/nsxctl#12]
add command to show NSX Manager version info

**Comment by hichtakk** [comment]
I'm looking for suitable api to get the version. If you have any idea, please let me know.

**Comment by mu853** [comment]
I found the following

$ nsxctl exec get /api/v1/node/version
{
  "node_version": "3.2.0.1.0.19232400",
  "product_version": "3.2.0.1.0.19232396"
}
$

**Comment by hichtakk** [comment]
PR merged
