### ISSUE TITLE
SIGSEGV occurs when wrong api passed to exec subcommand

### ISSUE THREAD

**Issue by mu853** [hichtakk/nsxctl#8]
$ nsxctl exec get /api/xxxxx --alb
2022/07/09 21:58:52 invalid character '<' looking for beginning of value
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x6a38a6]

goroutine 1 [running]:
github.com/hichtakk/nsxctl/client.(*Response).Print(0xc0000a6960?, 0xd3?)
	/home/ubuntu/nsxctl/client/request.go:45 +0xa6
github.com/hichtakk/nsxctl/cmd.NewCmdHttpGet.func1(0xc000155180?, {0xc0000c6880, 0x1, 0x2?})
	/home/ubuntu/nsxctl/cmd/exec.go:96 +0x20a
github.com/spf13/cobra.(*Command).execute(0xc000155180, {0xc0000c6860, 0x2, 0x2})
	/home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000d3680)
	/home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
	/home/ubuntu/nsxctl/main.go:9 +0x25
$

**Comment by hichtakk** [comment]
@mu853 I have corrected this issue. Please try latest code.

**Comment by mu853** [comment]
Thanks for your quick fix.
but still the error occurs if the api does not start with "/api/" like following.

$ nsxctl exec get xxxx
path must start with "/api/" or "/policy/"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x12a3f08]

goroutine 1 [running]:
github.com/hichtakk/nsxctl/client.(*Response).Print(0xc0001308c0?, 0x72?)
	/Users/myoichi/Desktop/nsxctl/client/request.go:46 +0xa8
github.com/hichtakk/nsxctl/cmd.NewCmdHttpGet.func1(0xc0001e3400?, {0xc00010ba80, 0x1, 0x1?})
	/Users/myoichi/Desktop/nsxctl/cmd/exec.go:96 +0x20a
github.com/spf13/cobra.(*Command).execute(0xc0001e3400, {0xc00010ba60, 0x1, 0x1})
	/Users/myoichi/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0xc000157680)
	/Users/myoichi/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/myoichi/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
	/Users/myoichi/Desktop/nsxctl/main.go:9 +0x25
$

**Comment by hichtakk** [comment]
Thank you for the report. I have fixed it.
